server:
  port: 80x2+2

spring:
  profiles:
    active: qa

  # Step 22 multiple profiles for multiple databases
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 
    password: 
    url: jdbc:mysql://localhost:3306/db_name
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  some:
    config: Welcome to the world of Spring Boot

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/db_name
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  some:
    config: Welcome to the world of Spring Boot
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/db_name
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  some:
    config: Welcome to the world of Spring Boot
